name: pf-hrp2-hrp3
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - fastp
  - fastqc
  - bwa
  - samtools
  - bcftools
  - bedtools
  - htslib
  - pysam
  - snpeff
  - openjdk=21